apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kluctl-webui-admin-role
rules:
  - apiGroups:
      - gitops.kluctl.io
    resources:
      - kluctldeployments
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  # Read access for all other Kubernetes objects
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: controller
    app.kubernetes.io/instance: kluctl-webui-rolebinding
    app.kubernetes.io/managed-by: kluctl
    app.kubernetes.io/name: clusterrolebinding
    app.kubernetes.io/part-of: controller
  name: kluctl-webui-admin-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kluctl-webui-admin-role
subjects:
  - kind: User
    apiGroup: rbac.authorization.k8s.io
    name: kluctl-webui-admin
